spring.application.name=weatherapi

spring.threads.virtual.enabled=true

weather.api.open-meteo.base-url=https://api.open-meteo.com/v1
weather.api.geoapify.base-url=https://api.geoapify.com/v1
weather.api.geoapify.api-key=${GEOAPIFY_API_KEY}

# Caching limits and expiration
weather.cache.expire.duration=10m
weather.cache.geo.limit=1000
weather.cache.weather.limit=1000
